name: BAD
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - absl-py=1.4.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - async-timeout=4.0.2
  - asynctest=0.13.0
  - attrs=22.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.19.0
  - ca-certificates=2023.05.30
  - catalogue=2.0.8
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.0.4
  - colorama=0.4.5
  - cryptography=35.0.0
  - cudatoolkit=11.0.221
  - cycler=0.11.0
  - cymem=2.0.6
  - cython-blis=0.7.7
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - expat=2.4.9
  - fftw=3.3.9
  - filelock=3.8.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - frozenlist=1.3.3
  - giflib=5.2.1
  - glib=2.69.1
  - h5py=3.7.0
  - hdf5=1.10.6
  # - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - importlib-metadata=4.11.4
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.0
  - jpeg=9b
  - jsonschema=3.0.2
  - jupyter_client=7.4.9
  - jupyter_core=4.11.2
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.4.2
  - langcodes=3.3.0
  - lcms2=2.12
  - libffi=3.3
  - libiconv=1.16
  - libpng=1.6.37
  - libprotobuf=3.15.8
  - libsodium=1.0.18
  - libtiff=4.1.0
  - libuv=1.40.0
  - libwebp=1.2.0
  - libxcb=1.15
  - libxml2=2.9.14
  - lz4-c=1.9.3
  # - m2w64-gcc-libgfortran=5.3.0
  # - m2w64-gcc-libs=5.3.0
  # - m2w64-gcc-libs-core=5.3.0
  # - m2w64-gmp=6.1.0
  # - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.4.3
  - markupsafe=2.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  # - msys2-conda-epoch=20160418
  - multidict=6.0.2
  - murmurhash=1.0.7
  - nb_conda_kernels=2.3.1
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.5.0
  - nest-asyncio=1.5.6
  - ninja=1.10.2
  - ninja-base=1.10.2
  - notebook=6.4.12
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1v
  - packaging=21.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathy=0.6.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - preshed=3.0.6
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pydantic=1.8.2
  - pygments=2.11.2
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.7.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.7
  - pytorch=1.7.1
  # - pywin32=305
  # - pywinpty=2.0.10
  - pyzmq=23.2.0
  - qt=5.9.7
  - requests=2.28.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - send2trash=1.8.0
  - setuptools=63.4.1
  - shellingham=1.5.0
  - sip=4.19.8
  - six=1.16.0
  - smart_open=5.2.1
  - soupsieve=2.3.2.post1
  - spacy=3.3.1
  - spacy-legacy=3.0.10
  - spacy-loggers=1.0.3
  - sqlite=3.39.3
  - srsly=2.4.3
  - tensorboard-plugin-wit=1.8.1
  - terminado=0.17.1
  - testpath=0.6.0
  - thinc=8.0.15
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - torchaudio=0.7.2
  - torchvision=0.8.2
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.7.1
  - trimesh=3.15.3
  - typer=0.4.2
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - urllib3=1.26.15
  # - vc=14.2
  # - vs2015_runtime=14.29.30133
  - wasabi=0.10.1
  - webencodings=0.5.1
  - werkzeug=2.2.3
  - wheel=0.37.1
  # - win_inet_pton=1.1.0
  # - wincertstore=0.2
  # - winpty=0.4.3
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yarl=1.8.1
  - zeromq=4.3.4
  - zipp=3.8.1
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
      - cachetools==5.3.1
      - chumpy==0.70
      # - clip==1.0
      - einops==0.6.1
      - fsspec==2023.1.0
      - ftfy==6.1.1
      - gdown==4.7.1
      - google-auth==2.22.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.57.0
      - huggingface-hub==0.16.4
      - oauthlib==3.2.2
      - plotly==5.18.0
      - protobuf==3.20.3
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyyaml==6.0.1
      - regex==2023.8.8
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - safetensors==0.4.5
      - smplx==0.1.28
      - tenacity==8.2.3
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - timm==0.9.12
      - wcwidth==0.2.6
